import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
      <Header />
       <main> {children}</main>
      <Footer />
      </body>
    </html>
  );
}
